iskedyul/urls.py
from django.urls import path

from iskedyul import forms, views

urlpatterns = [
    path("timetables/new/", views.create_timetable, name="create_timetable"),
    path("timetables/save/", views.save_timetable, name="save_timetable"),
    path("timetables/", views.timetable_list, name="timetable_list"),
    path("timetables/<int:timetable_id>/", views.edit_timetable, name="edit_timetable"),
    path("timetables/<int:timetable_id>/delete/", views.delete_timetable_dialog, name="delete_timetable_dialog"),
    path("timetables/delete/", views.delete_timetable, name="delete_timetable"),

    path("events/save/", forms.save_event, name="save_event"),
    path(
        "timetable/<int:timetable_id>/events/<int:id>/", 
        views.edit_event, name="edit_event",
    ),
    path(
        "timetables/<int:timetable_id>/events/<int:event_id>/delete", 
        views.delete_event_dialog, 
        name="delete_event_dialog"
    ),
    path("events/delete/", forms.delete_event, name="delete_event"),
    
]

server/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.urls import reverse

from iskedyul import views


def home(request):
    return redirect(reverse(views.timetable_list))

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__", include("django_browser_reload.urls")),
    path("", home),
    path("", include("iskedyul.urls")),
]

iskedyul/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from iskedyul import querysets

# Create your models here.


class Timetable(models.Model):
    """Model definition for Timetable."""

    title = models.CharField(_("title"), max_length=50)

    class Meta:
        """Meta definition for Timetable."""

        verbose_name = "Timetable"
        verbose_name_plural = "Timetables"

    def __str__(self):
        """Unicode representation of Timetable."""
        return self.title


class Days(models.IntegerChoices):
    MONDAY = 1, _("Monday")
    TUESDAY = 2, _("Tuesday")
    WEDNESDAY = 3, _("Wednesday")
    THURSDAY = 4, _("Thursday")
    FRIDAY = 5, _("Friday")
    SATURDAY = 6, _("Saturday")
    SUNDAY = 7, _("Sunday")


class Event(models.Model):
    """Model definition for Event."""

    timetable = models.ForeignKey(
        Timetable,
        verbose_name=_("timetable"),
        on_delete=models.CASCADE,
        related_name="events",
    )
    text = models.TextField(_("text"))
    day = models.IntegerField(_("day"), choices=Days.choices)
    start_time = models.TimeField(_("start time"))
    end_time = models.TimeField(_("end time"))

    objects = querysets.EventQuerySet.as_manager()

    class Meta:
        """Meta definition for Event."""

        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        """Unicode representation of Event."""
        return self.timetable.title + " - (" + Days(self.day).label + ") " + self.text

iskedyul/forms.py
from django import forms
from django.shortcuts import redirect
from .models import Timetable, Event


class TimetableForm(forms.ModelForm):
    class Meta:
        model = Timetable
        fields = ["title"]


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ["timetable", "text", "day", "start_time", "end_time"]


def save_event(request):
    try:
        event = Event.objects.get(pk=request.POST.get("id"))
        form = EventForm(request.POST or None, instance=event)
    except:  # noqa: E722
        form = EventForm(request.POST or None)
        print(request.POST)
    if form.is_valid():
        form.save()
    return redirect(request.POST.get("next_url"))


def delete_event(request):
    if request.POST.get("button_choice") == "ok":
        event = Event.objects.get(pk=request.POST.get("id"))
        event.delete()
        return redirect(request.POST.get("ok_url"))
    else:
        return redirect(request.POST.get("cancel_url"))

iskedyul/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from iskedyul import presenters
from iskedyul.forms import EventForm, TimetableForm
from iskedyul.models import Event, Timetable

# Create your views here.


def create_timetable(request):
    template_name = "iskedyul/pages/create_timetable.html"
    context = {
        "form_action": reverse(save_timetable),
        "next_url": reverse(timetable_list),
    }
    return render(request, template_name, context)


def save_timetable(request):
    try:
        timetable = Timetable.objects.get(pk=request.POST.get("id"))
        form = TimetableForm(request.POST or None, instance=timetable)
    except:  # noqa: E722
        form = TimetableForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect(request.POST.get("next_url"))


def timetable_list(request):
    template_name = "iskedyul/pages/timetable_list.html"
    context = {"timetables": Timetable.objects.all()}
    return render(request, template_name, context)


def edit_timetable(request, timetable_id, event=None):
    template_name = "iskedyul/pages/edit_timetable.html"
    timetable = Timetable.objects.get(pk=timetable_id)
    context = {
        "form_action": reverse(save_timetable),
        "next_url": reverse(edit_timetable, kwargs={"timetable_id": timetable_id}),
        "timetable": timetable,
        "event": event,
        "table": presenters.TimetableViewer(timetable.events),
    }
    return render(request, template_name, context)


def delete_timetable_dialog(request, timetable_id):
    template_name = "iskedyul/pages/delete_timetable.html"
    context = {
        "form_action": reverse(delete_timetable),
        "timetable": Timetable.objects.get(pk=timetable_id),
        "ok_url": reverse(timetable_list),
        "cancel_url": reverse(edit_timetable, kwargs={"timetable_id": timetable_id}),
    }
    return render(request, template_name, context)


def delete_timetable(request):
    if request.POST.get("button_choice") == "ok":
        timetable = Timetable.objects.get(pk=request.POST.get("id"))
        timetable.delete()
        next_url = request.POST.get("ok_url")
    else:
        next_url = request.POST.get("cancel_url")
    return redirect(next_url)


def edit_event(request, timetable_id, id):
    event = Event.objects.get(timetable_id=timetable_id, pk=id)
    return edit_timetable(request, timetable_id, event)


def delete_event_dialog(request, timetable_id, event_id):
    template_name = "iskedyul/pages/delete_event.html"
    event = Event.objects.get(pk=event_id)
    timetable = Timetable.objects.get(pk=timetable_id)
    context = {
        "event": event,
        "ok_url": reverse(edit_timetable, kwargs={
            "timetable_id": timetable_id,
        }),
        "cancel_url": reverse(edit_event, kwargs={
            "timetable_id": timetable_id, 
            "id": event.id,
        }),
        "timetable": timetable,
        "table": presenters.TimetableViewer(timetable.events),
    }
    return render(request, template_name, context)

iskedyul/templates/iskedyul/components/card.html
<div class="card h-100">
    <div class="card-body">
        {% block card_body %}
        {% endblock card_body %}
    </div>
</div>

iskedyul/templates/iskedyul/components/delete_event_dialog.html
{% extends 'iskedyul/components/card.html' %}
{% block card_body %}
    <form method="post" action="{% url 'delete_event' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md">
                <div class="row">
                    <div class="col-md-4">
                        <label for="id_text"  class="form-label">Text</label>
                        <textarea rows="3" id="id_text" name="text" class="form-control" disabled>{{ event.text }}</textarea>
                    </div>
                    <div class="col">
                        <div class="row">
                            <div class="col-12">
                                <div class="d-inline">Time: {{ event.start_time|time:'H:i' }}-{{ event.end_time|time:'H:i' }}</div>
                                <div class="d-inline">
                                    (
                                    {% if event.day == 1 %}Monday{% endif %}
                                    {% if event.day == 2 %}Tuesday{% endif %}
                                    {% if event.day == 3 %}Wednesday{% endif %}
                                    {% if event.day == 4 %}Thursday{% endif %}
                                    {% if event.day == 5 %}Friday{% endif %}
                                    {% if event.day == 6 %}Saturday{% endif %}
                                    {% if event.day == 7 %}Sunday{% endif %}
                                    )
                                </div>
                            </div>
                            <div class="col-12">
                                <p>
                                    Are you sure you want to delete this event?<br>
                                    This cannot be undone.
                                </p>
                            </div>
                            <div class="col-12">
                                <button type="submit"
                                        name="button_choice"
                                        value="cancel"
                                        class="btn btn-secondary">Cancel</button>
                                <button type="submit" name="button_choice" value="ok" class="btn btn-danger">OK</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" name="id" value="{{ event.id }}">
        <input type="hidden" name="ok_url" value="{{ ok_url }}">
        <input type="hidden" name="cancel_url" value="{{ cancel_url }}">
    </form>
{% endblock card_body %}

iskedyul/templates/iskedyul/components/delete_timetable_dialog.html
{% extends 'iskedyul/components/card.html' %}
{% block card_body %}
    <form method="post" action="{{ form_action }}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md">
                <p>{{ timetable.title }}</p>
                <p>
                    Are you sure you want to delete this timetable?
                    This cannot be undone.
                </p>
            </div>
        </div>
        <input type="hidden" name="id" value="{{ timetable.id }}">
        <input type="hidden" name="ok_url" value="{{ ok_url }}">
        <input type="hidden" name="cancel_url" value="{{ cancel_url }}">
        <button type="submit" name="button_choice" value="cancel" class="btn btn-secondary">Cancel</button>
        <button type="submit" name="button_choice" value="ok" class="btn btn-danger">OK</button>
    </form>
{% endblock card_body %}

iskedyul/templates/iskedyul/components/event_form.html
{% extends 'iskedyul/components/card.html' %}
{% block card_body %}

    <form method="post" action="{% url 'save_event' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="id_text"  class="form-label">Text</label>
                <textarea rows="3" id="id_text" name="text" class="form-control" required>{{ event.text }}</textarea>
            </div>
            <div class="col">
                <div class="row">
                    <div class="col">
                        <div class="mb-3">
                            <label for="id_start_time"  class="form-label">Start time</label>
                            <input type="time"
                                   id="id_start_time"
                                   name="start_time"
                                   class="form-control"
                                   value="{{ event.start_time|time:'H:i' }}"
                                   placeholder="Select start time.."
                                   required>
                        </div>
                    </div>
                    <div class="col">
                        <div class="mb-3">
                            <label for="id_end_time"  class="form-label">End time</label>
                            <input type="time"
                                   id="id_end_time"
                                   name="end_time"
                                   class="form-control"
                                   value="{{ event.end_time|time:'H:i' }}"
                                   placeholder="Select end time.."
                                   required>
                        </div>
                    </div>
                    <div class="col">
                        <div class="mb-3">
                            <label for="id_day" class="form-label">Day</label>
                            <select id="id_day" name="day" class="form-select" required>
                                <option selected>Select day..</option>
                                <option value="1" {% if event.day == 1 %}selected{% endif %}>Monday</option>
                                <option value="2" {% if event.day == 2 %}selected{% endif %}>Tuesday</option>
                                <option value="3" {% if event.day == 3 %}selected{% endif %}>Wednesday</option>
                                <option value="4" {% if event.day == 4 %}selected{% endif %}>Thursday</option>
                                <option value="5" {% if event.day == 5 %}selected{% endif %}>Friday</option>
                                <option value="6" {% if event.day == 6 %}selected{% endif %}>Saturday</option>
                                <option value="7" {% if event.day == 7 %}selected{% endif %}>Sunday</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% if event %}
                            <a href="{% url 'edit_timetable' timetable.id %}"
                               class="btn btn-secondary">Cancel</a>
                            {% include 'iskedyul/components/save_button.html' with button_text='Save event' %}
                        {% else %}
                            {% include 'iskedyul/components/save_button.html' with button_text='Create event' %}
                        {% endif %}
                        {% if event %}
                            <a href="{% url 'delete_event_dialog' event.timetable.id event.id %}"
                               class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <input type="hidden" name="timetable" value="{{ timetable.id }}">
        <input type="hidden" name="id" value="{{ event.id }}">
        <input type="hidden" name="next_url" value="{{ next_url }}">
    </form>
    {% include 'iskedyul/components/flatpickr_script.html' %}
{% endblock card_body %}

iskedyul/templates/iskedyul/components/flatpickr_script.html
{% load static %}
<script src="{% static 'flatpickr/flatpickr.js' %}"></script>
<script>

  const startTimePicker = flatpickr("#id_start_time", {
      enableTime: true,            // Enable time selection
      noCalendar: true,           // Hide the calendar
      dateFormat: "H:i",          // Time format (24-hour)
      time_24hr: true,
      minDate: "07:00",           // Minimum time (7:00 AM)
      maxDate: "20:30",           // Maximum time (8:30 PM)
      minuteIncrement: 30,        // Set minute step to 30 minutes
  });
  const endTimePicker = flatpickr("#id_end_time", {
      enableTime: true,            // Enable time selection
      noCalendar: true,           // Hide the calendar
      dateFormat: "H:i",          // Time format (24-hour)
      time_24hr: true,
      maxDate: "20:30",           // Maximum time (8:30 PM)
      minuteIncrement: 30,        // Set minute step to 30 minutes
  });

  

  // Set the minDate of the end time picker based on the selected start time
  startTimePicker.config.onClose.push(function(selectedDates, dateStr, instance) {
    const startTime = instance.parseDate(dateStr, "H:i");

    // Set min end time to be 30 minutes later than the selected start time
    const newMinDate = new Date(startTime.getTime() + 30 * 60000);
    endTimePicker.set("minDate", newMinDate);
  });
  
  endTimePicker.config.onOpen.push(function(selectedDates, dateStr, instance) {
    // Set the minDate of the end time picker based on the selected start time
    const startTime = instance.parseDate(startTimePicker.input.value, "H:i");

    if (!startTime) {
      instance.set("minDate", "07:30");
    } else {
      // Set min end time to be 30 minutes later than the selected start time
      const newMinDate = new Date(startTime.getTime() + 30 * 60000);
      instance.set("minDate", newMinDate);
    }
  });
</script>

iskedyul/templates/iskedyul/components/navbar.html
<!-- Navbar -->
<nav class="navbar">
    <div class="container-fluid justify-content-center">
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'timetable_list' %}">
                        <h1>ISKEDYUL</h1>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

iskedyul/templates/iskedyul/components/save_button.html
<button type="submit" class="btn btn-primary">{{ button_text }}</button>

iskedyul/templates/iskedyul/components/timetable_form.html
{% extends 'iskedyul/components/card.html' %}
{% block card_body %}
    <form method="post" action="{{ form_action }}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md">
                <div class="mb-3">
                    <label for="title"  class="form-label">Title</label>
                    <input type="text" id="title" name="title" value="{{ timetable.title }}" placeholder="Enter title" class="form-control">
                </div>
            </div>
        </div>
        <input type="hidden" name="next_url" value="{{ next_url }}">
        {% include 'iskedyul/components/save_button.html' with button_text='Save timetable' %}
        {% if timetable %}
        <input type="hidden" name="id" value="{{ timetable.id }}">
        <a href="{% url 'delete_timetable_dialog' timetable.id %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </form>
{% endblock card_body %}

iskedyul/templates/iskedyul/components/timetable_item_card.html
{% extends 'iskedyul/components/card.html' %}
{% block card_body %}
    {% if timetable %}
        <a class="stretched-link" href="{% url 'edit_timetable' timetable.id %}"></a>
        <h5 class="card-title">{{ timetable.title }}</h5>
        <p class="card-text">id: {{ timetable.id }}</p>
    {% else %}
        <a class="stretched-link" href="{% url 'create_timetable' %}"></a>
        <h5 class="card-title">New..</h5>
        <p class="card-text">Click to create a new timetable.</p>
    {% endif %}
{% endblock card_body %}

iskedyul/templates/iskedyul/components/timetable_viewer.html
<div class="border border-secondary-subtle rounded rounded-3"  id="printableArea">
    <style>
        /* Add custom CSS for equal-width columns */
        .table-fixed {
            table-layout: fixed;
            width: 100%;
        }
        .table-fixed th, .table-fixed td {
            width: 20%; /* Set equal width for each column (adjust as needed) */
            text-align: center; /* Center-align text within cells */
        }
        .tbody-tr-fixed tr {
            height: 20px;
        }
    </style>
    <table class="table table-sm table-bordered border rounded overflow-hidden m-0 caption-top table-fixed">
        <caption class="text-center fw-bold">{{ timetable.title }}</caption>
        <thead>
            <tr>
                <th>TIME</th>
                {% for th in table.head %}<th scope="colgroup" colspan="{{ th.colspan }}">{{ th.day.label|upper }}</th>{% endfor %}
            </tr>
        </thead>
        <tbody class="tbody-tr-fixed">
            {% for interval, row in table.body.items %}
                <tr>
                    <th scope="row" class="fw-normal">{{ interval.start|time:"h:i" }}-{{ interval.end|time:'h:i A' }}</th>
                    {% for td in row %}
                        {% if td is not None %}
                            {% if td.empty %}
                                <td></td>
                            {% else %}
                                <td rowspan="{{ td.rowspan }}" class="bg-body-secondary">
                                    <a href="{% url 'edit_event' timetable.id td.event.id %}"
                                       class="link-underline link-underline-opacity-0">{{ td.event.text|linebreaks }}</a>
                                </td>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    document.addEventListener("keydown", function(event) {
        // Check if Ctrl (or Cmd on Mac) and P keys are pressed simultaneously
        if ((event.ctrlKey || event.metaKey) && event.key === "p") {
            event.preventDefault(); // Prevent the default print dialog
            printTable();
        }
    });

    function addDPrintNoneToAllExceptTableAndElementsWithClass(className) {
        // Get all elements on the page
        const allElements = document.querySelectorAll("*");
      
        // Iterate over all elements
        for (const element of allElements) {
          // Check if the element is a table or a table element, or if it has the specified class name
          if (element.tagName !== "TABLE" && !element.closest("TABLE") && !element.classList.contains(className)) {
            // Add the "d-print-none" CSS class to the element
            element.classList.add("d-print-none");
          }
        }
      }
      
    
    function printTable() {
        var originalContents = document.body.innerHTML;
        var printContents = document.getElementById('printableArea').outerHTML;
        
        document.body.innerHTML = printContents;
        
        window.print();
        
        document.body.innerHTML = originalContents;
    }
</script>

iskedyul/templates/iskedyul/pages/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link href="{% static 'bootstrap-5.3.1-dist/css/bootstrap.min.css' %}"
              rel="stylesheet">
        <link href="{% static 'flatpickr/flatpickr.min.css' %}" rel="stylesheet">
        <title>
            {% block title %}
                Iskedyul
            {% endblock title %}
        </title>
    </head>
    <body class="d-flex flex-column vh-100 ">
        <header>
            {% include 'iskedyul/components/navbar.html' %}
        </header>
        <main class="container flex-grow-1">
            {% block content %}
                This content will be replaced by different html code for each page.
            {% endblock content %}
        </main>
        <footer class="mt-auto footer text-center">
            <div class="p-4 height-auto">
                BSIT 3D
                <br>
                IT 373
            </div>
        </footer>
        <script src="{% static 'unpkg.com_@popperjs_core@2.11.8_dist_umd_popper.min.js' %}"></script>
        <script src="{% static 'bootstrap-5.3.1-dist/js/bootstrap.min.js' %}"></script>
    </body>
</html>

iskedyul/templates/iskedyul/pages/center_base.html
{% extends 'iskedyul/pages/base.html' %}
{% block content %}
    <div class="row g-4">
        <div class="col-md-8 col-lg-4 mx-auto">
            {% block center %}
            {% endblock center %}
        </div>
    </div>
{% endblock content %}

iskedyul/templates/iskedyul/pages/create_timetable.html
{% extends 'iskedyul/pages/center_base.html' %}
{% block center %}
    {% include 'iskedyul/components/timetable_form.html' %}
{% endblock center %}

iskedyul/templates/iskedyul/pages/delete_event.html
{% extends 'iskedyul/pages/edit_timetable.html' %}
{% block topleft %}
    {% include 'iskedyul/components/timetable_form.html' %}
{% endblock topleft %}
{% block topright %}
    {% include 'iskedyul/components/delete_event_dialog.html' %}
{% endblock topright %}
{% block main %}
    {% include 'iskedyul/components/timetable_viewer.html' %}
{% endblock main %}

iskedyul/templates/iskedyul/pages/delete_timetable.html
{% extends 'iskedyul/pages/center_base.html' %}
{% block center %}
    {% include 'iskedyul/components/delete_timetable_dialog.html' %}
{% endblock center %}

iskedyul/templates/iskedyul/pages/edit_timetable.html
{% extends 'iskedyul/pages/base.html' %}
{% block content %}
    <div class="row g-4">
        <div class="col">{% include 'iskedyul/components/timetable_form.html' %}</div>
    </div>
{% endblock content %}

iskedyul/templates/iskedyul/pages/timetable_base.html
{% extends 'iskedyul/pages/base.html' %}
{% block content %}
    <div class="row g-4">
        <div class="col-md">
            {% block topleft %}
            {% endblock topleft %}
        </div>
        <div class="col-md-8">
            {% block topright %}
            {% endblock topright %}
        </div>
        <div class="col-12">
            {% block main %}
            {% endblock main %}
        </div>
    </div>
{% endblock content %}

iskedyul/templates/iskedyul/pages/timetable_list.html
{% extends 'iskedyul/pages/base.html' %}
{% block title %}
    Timetables - Iskedyul
{% endblock title %}
{% block content %}
    <div class="container justify-content-center">
        <div class="row g-4">
            <div class="col-12">{% include 'iskedyul/components/timetable_item_card.html' %}</div>
            {% for timetable in timetables %}
                <div class="col-md-12">{% include 'iskedyul/components/timetable_item_card.html' %}</div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}